tpf_django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from apps.core import  views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('accounts/', include('allauth.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "TPF Admin"
admin.site.site_title = "TPF Admin Portal"
admin.site.index_title = "Admin | TPF"

apps/core/models.py
from django.db import models
from solo.models import SingletonModel
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class About(SingletonModel):
    
    title= models.CharField(max_length=100, null=False)
    description= models.TextField()
    def __str__(self):
            return self.title

    class Meta:
        verbose_name = "How It Works"

class Term(SingletonModel):
    
    title= models.CharField(max_length=100, null=False)
    description= models.TextField()
    def __str__(self):
            return self.title
    class Meta:
        verbose_name = "Terms of Service"

class Parent(models.Model):
        name = models.CharField(max_length=255, null=False, unique=True)
        slug = models.SlugField(null=True, max_length=255, blank=True)
        meta_desctrption = models.TextField()
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)

        def save(self, *args, **kwargs):
            self.slug = slugify(self.name)
            super(Parent, self).save(*args, **kwargs)

        def __str__(self):
                return self.name

class Child(models.Model):
        parent = models.ForeignKey(Parent, on_delete=models.CASCADE)
        name = models.CharField(max_length=255, null=False, unique=True)
        slug = models.SlugField(null=True, max_length=255, blank=True)
        
        meta_description = models.TextField()
        days = models.IntegerField(null=False)
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)

        def save(self, *args, **kwargs):
            self.slug = slugify(self.name)
            super(Child, self).save(*args, **kwargs)

        def __str__(self):
                return self.name



class ListFebric(models.Model):
        CHOICES = [('1', 'Contact me Directly'), ('2', 'Conduct Sale at Another Location')]
        parent = models.ForeignKey(Parent, on_delete=models.CASCADE)
        child = models.ForeignKey(Child, on_delete=models.CASCADE)
        title = models.CharField(max_length=255, null=False, unique=True, error_messages={'unique':"The title is already taken."})
        price = models.IntegerField(null=False)
        sell_at = models.CharField(max_length=2,choices=CHOICES,default=1)
        link_ebay = models.URLField(max_length=255 ,null=False, blank=False)
        facebook_profile = models.URLField(max_length=255, null=False, blank= False)
        instagram_profile = models.URLField(max_length=255, null=False, blank=False)
        user = models.ForeignKey(User,on_delete=models.CASCADE, null=False, blank=False)
        email = models.EmailField(null=False, blank=False)
        phone = PhoneNumberField()
        slug = models.SlugField(max_length=255, blank=True, null=True)
        short_description = models.TextField()
        long_description = models.TextField()
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)

        def save(self, *args, **kwargs):
            self.slug = slugify(self.title)
            super(ListFebric, self).save(*args, **kwargs)

        def __str__(self):
                return self.title

class MultiStepFormModel(models.Model):
    id=models.AutoField(primary_key=True)
    fname=models.CharField(max_length=255)
    lname=models.CharField(max_length=255)
    phone=models.CharField(max_length=255)
    twitter=models.CharField(max_length=255)
    facebook=models.CharField(max_length=255)
    gplus=models.CharField(max_length=255)
    email=models.CharField(max_length=255)
    password=models.CharField(max_length=255)
    objects=models.Manager()








        

templates/about.html
{% extends "partials/base.html" %} 
{% load static %}
{% block navbar %}
    {% include 'partials/navbar.html' %}
{% endblock navbar %}


{% block main %}
<div id="body">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="about-title">
                    <h2 class="text-center mt-5 mb-5">{{about.title}}</h2>
                    <p class="mt-5 mb-5">{{about.description}}</p>
                </div>
            </div>
        </div>    
    </div>
</div>
{% endblock main %}


{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock footer %}
    

templates/child_dropdown_list.html
<option value="">---------</option>
{% for child in childs %}
<option value="{{ child.pk }}">{{ child.name }}</option>
{% endfor %}

templates/index.html
{% extends "partials/base.html" %} 
{% load static %}
{% block navbar %}
    {% include 'partials/navbar.html' %}
{% endblock navbar %}


{% block main %}
<div id="body">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="banner-title">
                    <div class="top-heading mt-5 mb-5">
                        <h1 class="text-center">Find Your Favourite Out of Print</h1>
                    </div>
                    <div class="bottom-heading">
                        <h3 class="text-center">Start by Selecting A Collection</h3>
                    </div>
                </div>
            </div>
        </div>    
        <div class="row">
            <div class="col-md-6">
                <div class="select-febric-by-parent mt-5">
                    <div class="input-group mb-3">
                        {{ form.parent }} 
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="select-febric-by-child mt-5">
                    <div class="input-group mb-3">
                        {{ form.child }}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="febric-cat mt-5">
                    <p class="text-center">or <br> View All Febrics</p>
                </div>
                <div class="list-febric">
                    <ul>
                        <li> <a href="#" >TPF1</a>
                          <ul>
                            <li><a href="#" >Red Febrics</a></li>
                            <li><a href="#" >Blue Febrics</a></li>
                          </ul>
                        </li>
                        <li> <a href="#" >TPF2</a>
                            <ul>
                              <li><a href="#" >Purple Febrics</a></li>
                              <li><a href="#" >Orange Febrics</a></li>
                            </ul>
                          </li>
                      </ul>                      
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}


{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock footer %}
    

templates/search_febrics.html
{% extends "partials/base.html" %} 
{% load static %}
{% block navbar %}
    {% include 'partials/navbar.html' %}
{% endblock navbar %}


{% block main %}
<div id="body">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="banner-title">
                    <div class="top-heading mt-5 mb-5">
                        <h1 class="text-center">Find Your Favourite Out of Print</h1>
                    </div>
                </div>
            </div>
        </div>     
        <div class="row infinite-container">
        {% for post in list_febrics %}
            <div class="col-md-4 infinite-item">
                    <div class="card mb-3">
                        <img src="https://newhorizon-department-of-civil-engineering.s3.ap-south-1.amazonaws.com/nhengineering/department-of-civil-engineering/wp-content/uploads/2020/01/13102231/default-image.png" class="card-img-top" alt="...">
                        <div class="card-body">
                            <div class="d-flex bd-highlight mb-3">
                                <div class="p-2 bd-highlight"><p class="card-text"><small class="text-muted"><i class="fa fa-star"></i>{{ post.created_at| date:"M d" }}</small></p></div>
                                <div class="p-2 bd-highlight"><a href="#" class="card-title">{{post.title}}</a></div>
                                <div class="p-2 bd-highlight"><p class="card-text"><small class="text-muted">${{post.price}}</small></p></div>
                            </div>
                            <p class="card-text"><small class="text-muted">(hayward / castro valley)</small></p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        <div class="loading" style="display: none;">
                <p>Loading....</p>
        </div>
        {% if page_obj.has_next %}
            <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
        {% endif %}
        <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
        <script src="/static/js/infinite.min.js"></script>
        <script>
            var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
            }
            });
        </script>   
    </div>
</div>
{% endblock main %}


{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock footer %}
    

templates/submit_a_list.html
{% extends "partials/base.html" %} 
{% load static %}
{% block navbar %}
    {% include 'partials/navbar.html' %}
{% endblock navbar %}


{% block main %}
<style>

  /*form styles*/
  #msform {
      text-align: center;
      position: relative;
      margin-top: 30px;
  }

  #msform fieldset {
      background: white;
      border: 0 none;
      border-radius: 0px;
      box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);
      padding: 20px 30px;
      box-sizing: border-box;
      width: 80%;
      margin: 0 10%;

      /*stacking fieldsets above each other*/
      position: relative;
  }

  /*Hide all except first fieldset*/
  #msform fieldset:not(:first-of-type) {
      display: none;
  }

  /*inputs*/
  #msform input, #msform textarea {
      padding: 15px;
      border: 1px solid #ccc;
      border-radius: 0px;
      margin-bottom: 10px;
      width: 100%;
      box-sizing: border-box;
      font-family: montserrat;
      color: #2C3E50;
      font-size: 13px;
  }

  #msform input:focus, #msform textarea:focus {
      -moz-box-shadow: none !important;
      -webkit-box-shadow: none !important;
      box-shadow: none !important;
      border: 1px solid #ee0979;
      outline-width: 0;
      transition: All 0.5s ease-in;
      -webkit-transition: All 0.5s ease-in;
      -moz-transition: All 0.5s ease-in;
      -o-transition: All 0.5s ease-in;
  }

  /*buttons*/
  #msform .action-button {
      width: 100px;
      background: #ee0979;
      font-weight: bold;
      color: white;
      border: 0 none;
      border-radius: 25px;
      cursor: pointer;
      padding: 10px 5px;
      margin: 10px 5px;
  }

  #msform .action-button:hover, #msform .action-button:focus {
      box-shadow: 0 0 0 2px white, 0 0 0 3px #ee0979;
  }

  #msform .action-button-previous {
      width: 100px;
      background: #C5C5F1;
      font-weight: bold;
      color: white;
      border: 0 none;
      border-radius: 25px;
      cursor: pointer;
      padding: 10px 5px;
      margin: 10px 5px;
  }

  #msform .action-button-previous:hover, #msform .action-button-previous:focus {
      box-shadow: 0 0 0 2px white, 0 0 0 3px #C5C5F1;
  }

  /*headings*/
  .fs-title {
      font-size: 18px;
      text-transform: uppercase;
      color: #2C3E50;
      margin-bottom: 10px;
      letter-spacing: 2px;
      font-weight: bold;
  }

  .fs-subtitle {
      font-weight: normal;
      font-size: 13px;
      color: #666;
      margin-bottom: 20px;
  }

  /*progressbar*/
  #progressbar {
      margin-bottom: 30px;
      overflow: hidden;
      /*CSS counters to number the steps*/
      counter-reset: step;
  }

  #progressbar li {
      list-style-type: none;
      color: white;
      text-transform: uppercase;
      font-size: 9px;
      width: 33.33%;
      float: left;
      position: relative;
      letter-spacing: 1px;
  }

  #progressbar li:before {
      content: counter(step);
      counter-increment: step;
      width: 24px;
      height: 24px;
      line-height: 26px;
      display: block;
      font-size: 12px;
      color: #333;
      background: white;
      border-radius: 25px;
      margin: 0 auto 10px auto;
  }

  /*progressbar connectors*/
  #progressbar li:after {
      content: '';
      width: 100%;
      height: 2px;
      background: white;
      position: absolute;
      left: -50%;
      top: 9px;
      z-index: -1; /*put it behind the numbers*/
  }

  #progressbar li:first-child:after {
      /*connector not needed before the first step*/
      content: none;
  }

  /*marking active/completed steps green*/
  /*The number of the step and the connector before it = green*/
  #progressbar li.active:before, #progressbar li.active:after {
      background: #ee0979;
      color: white;
  }


  /* Not relevant to this form */
  .dme_link {
      margin-top: 30px;
      text-align: center;
  }
  .dme_link a {
      background: #FFF;
      font-weight: bold;
      color: #ee0979;
      border: 0 none;
      border-radius: 25px;
      cursor: pointer;
      padding: 5px 25px;
      font-size: 12px;
  }

  .dme_link a:hover, .dme_link a:focus {
      background: #C5C5F1;
      text-decoration: none;
  }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 style="color:#000;border:1px solid white;padding:10px;margin:15px;">List Submit Form</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mb-3">
            <form id="msform" action="{% url 'submit-list' %}" method="post" data-cities-url="{% url 'ajax_load_lists' %}" novalidate>
                {% csrf_token %}
                <!-- progressbar -->
                <ul id="progressbar">
                    <li class="active">Step 1</li>
                    <li>Step 2</li>
                    <li>Final Setup</li>
                </ul>
                <!-- fieldsets -->
                <fieldset>
                    <h2 class="fs-title">Select Parent & Child Fabrics</h2>
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% for field in form.visible_fields|slice:":2"  %}
                        <tr>
                            <td>
                                {{field.label_tag }}
                            </td>
                            <td>{{field}}</td>
                        </tr>
                        {% endfor %}
                    <input type="button" name="next" class="next action-button" value="Next"/>
                </fieldset>
                <fieldset>
                    <h2 class="fs-title">Fill Out all Form</h2>
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% for field in form.visible_fields|slice:"2:5"  %}
                        <tr>
                            <td>
                                {{field.label_tag }}
                            </td>
                            <td>{{field}}</td>
                        </tr>
                        {% endfor %}
                    <input type="button" name="previous" class="previous action-button-previous" value="Previous"/>
                    <input type="button" name="next" class="next action-button" value="Next"/>
                </fieldset>
                <fieldset>
                    <h2 class="fs-title">Fill Out all Form</h2>
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% for field in form.visible_fields|slice:"5:"  %}
                        <tr>
                            <td>
                                {{field.label_tag }}
                            </td>
                            <td>{{field}}</td>
                        </tr>
                        {% endfor %}
                    <input type="button" name="previous" class="previous action-button-previous" value="Previous"/>
                    <input type="submit" name="submit" class="submit action-button" value="Submit"/>
                </fieldset>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
    </div>
    <script>
        $("#id_parent").change(function () {
          var url = $("#msform").attr("data-cities-url");
          var parentId = $(this).val();
      
          $.ajax({
            url: url,
            data: {
              'parent': parentId
            },
            success: function (data) {
              $("#id_child").html(data);
            }
          });
      
        });
      </script>
    <script>
    
        //jQuery time
        var current_fs, next_fs, previous_fs; //fieldsets
        var left, opacity, scale; //fieldset properties which we will animate
        var animating; //flag to prevent quick multi-click glitches
    
        $(".next").click(function(){
            if(animating) return false;
            animating = true;
    
            current_fs = $(this).parent();
            next_fs = $(this).parent().next();
    
            //activate next step on progressbar using the index of next_fs
            $("#progressbar li").eq($("fieldset").index(next_fs)).addClass("active");
    
            //show the next fieldset
            next_fs.show();
            //hide the current fieldset with style
            current_fs.animate({opacity: 0}, {
                step: function(now, mx) {
                    //as the opacity of current_fs reduces to 0 - stored in "now"
                    //1. scale current_fs down to 80%
                    scale = 1 - (1 - now) * 0.2;
                    //2. bring next_fs from the right(50%)
                    left = (now * 50)+"%";
                    //3. increase opacity of next_fs to 1 as it moves in
                    opacity = 1 - now;
                    current_fs.css({
                'transform': 'scale('+scale+')',
                'position': 'absolute'
              });
                    next_fs.css({'left': left, 'opacity': opacity});
                },
                duration: 800,
                complete: function(){
                    current_fs.hide();
                    animating = false;
                },
                //this comes from the custom easing plugin
                easing: 'easeInOutBack'
            });
        });
    
        $(".previous").click(function(){
            if(animating) return false;
            animating = true;
    
            current_fs = $(this).parent();
            previous_fs = $(this).parent().prev();
    
            //de-activate current step on progressbar
            $("#progressbar li").eq($("fieldset").index(current_fs)).removeClass("active");
    
            //show the previous fieldset
            previous_fs.show();
            //hide the current fieldset with style
            current_fs.animate({opacity: 0}, {
                step: function(now, mx) {
                    //as the opacity of current_fs reduces to 0 - stored in "now"
                    //1. scale previous_fs from 80% to 100%
                    scale = 0.8 + (1 - now) * 0.2;
                    //2. take current_fs to the right(50%) - from 0%
                    left = ((1-now) * 50)+"%";
                    //3. increase opacity of previous_fs to 1 as it moves in
                    opacity = 1 - now;
                    current_fs.css({'left': left});
                    previous_fs.css({'transform': 'scale('+scale+')', 'opacity': opacity});
                },
                duration: 800,
                complete: function(){
                    current_fs.hide();
                    animating = false;
                },
                //this comes from the custom easing plugin
                easing: 'easeInOutBack'
            });
        });
    
    </script>
{% endblock main %}


{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock footer %}
    

templates/terms_of_service.html
{% extends "partials/base.html" %} 
{% load static %}
{% block navbar %}
    {% include 'partials/navbar.html' %}
{% endblock navbar %}


{% block main %}
<div id="body">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="about-title">
                    <h2 class="text-center mb-5 mt-5">{{ terms.title }}</h2>
                    <p class="mt-5 mb-5">{{ terms.description }}</p>
                </div>
            </div>
        </div>    
    </div>
</div>
{% endblock main %}


{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock footer %}
    